name: Build packages

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: windows-intel
            runs-on: windows-latest
          - os: windows-arm
            runs-on: windows-11-arm
          - os: macos-intel
            # macos-15-intel is the last x86_64 runner
            runs-on: macos-15-intel
          - os: macos-arm
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          persist-credentials: false

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        # env:
          # configure cibuildwheel on Linux to build native archs ('auto'),
          # and to split the remaining architectures between the x86_64 and
          # ARM runners
          # CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto ppc64le s390x' || 'auto' }}

      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          if-no-files-found: error
          retention-days: 7


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
          if-no-files-found: error
          retention-days: 7
